 # versão do composer vinculada a sua versão do docker (o meu é a versão 19.03). veja aqui: https://docs.docker.com/compose/compose-file/
# para ver sua versão do docker, digite o comando
# $ sudo docker -v
version: "3"

services:
    db:
        image: postgres # passando nome da imagem
        environment: 
            POSTGRES_PASSWORD: superSenha # passando a senha do meu banco
            POSTGRES_USER: postgres # passando o usuário do banco
            POSTGRES_DB: my_db # passando o nome do banco
        ports: 
            - "5433:5432" # a porta devo acessar na máquina real, e a porta exposta por esse container 
        volumes: 
            - ./pgdata:/var/lib/postgresql/data # de onde sairá os arquivos do banco para onde eles irão na máquina docker
    app:
        build: . # vai iniciar a máquina, passamos o diretório em que está o Dockerfile
        depends_on: # faz com que o container app só funcione se o container db estirver funcionando
            - "db"
        command: "yarn start" # o comando que será executado na inicialização. o script wait-for-it, faz com que a instancia app inicialize somente depois do banco de dados subir
        ports:
            - "3000:3000" # a porta devo acessar na máquina real, e a porta exposta por esse container
        volumes: 
            - .:/usr/app # quando isso aqui rodar (o que é sempre que houver modificações por conta do nodemon) copiaremos tudo de . para dentro da pasta /user/app da máquina docker
