version: "3"

services:
    db:
        image: postgres 
        environment: 
            POSTGRES_PASSWORD: superSenha
            POSTGRES_USER: postgres
            POSTGRES_DB: flask_db
        ports: 
            - "5434:5432"
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        networks: 
            - app-db-network
    app:
        build: .
        depends_on:
            - "db"
        command: "python server.py"
        ports:
            - "5000:5000"
        volumes: 
            - .:/usr/src/app
        networks: 
            - app-db-network
networks: 
    app-db-network:
        driver: bridge